targets:
  $default:
    sources:
      include:
        - $package$
        - lib/$lib$
        - lib/**
        - packages/**
    builders:
      json_serializable:
        options:
          explicit_to_json: true