name: agent_repository
description: Dart package which manages the agent domain.
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  langchain: ^0.0.7
  langchain_openai: ^0.0.7
  uuid: ^3.0.5
  flutter_dotenv: ^5.1.0

dev_dependencies:
  test: ^1.16.4
  very_good_analysis: ^2.4.0
