blank_issues_enabled: false
contact_links:
  - name: Flutter issue
    url: https://github.com/derek-x-wang/carnal/issues/new/choose
    about: I'm having an issue with Carnal itself.
  - name: Question
    url: https://stackoverflow.com/questions/tagged/carnal-flutter?tab=Frequent
    about: I have a question about Carnal.