name: authentication_repository
description: Dart package which manages the authentication domain.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.1
  meta: ^1.3.0
  equatable: ^2.0.3
  very_good_analysis: ^2.4.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  cache:
    path: ../cache
  local_storage:
    path: ../local_storage

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.1
  freezed: ^2.4.1
  json_serializable: ^6.7.1
