name: profiles_repository
description: Dart package which manages the user profiles.
version: 0.1.0+1
publish_to: none

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.27.3
  equatable: ^2.0.3
  uuid: ^3.0.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  local_storage:
    path: ../local_storage

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  json_serializable: ^6.7.1
