name: local_storage
description: Manage disk storage.
version: 1.0.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  synchronized: ^3.1.0
  uuid: ^3.0.5

dev_dependencies:
  test: ^1.16.4
  very_good_analysis: ^2.4.0
